### PR TITLE
Budget Binder App

### PR DESCRIPTION
**Pull request by IsmaelMastronardi**
### Budget Binder 
Budget Binder is a Ruby On Rails application designed to keep track of transactions. 

### Functionality :
- Allows the user to create an account or log in with an already created account.
- The user can create new categories to organize their transactions.
- The user can create new transactions and add them to one or more groups.
- The user can see all their groups and the transactions contained in them.

### Pages : 
The Application contains the following pages : 

- Home page :
Screenshot (118)

- Categories page :
Screenshot (119)

- Entities page :
Screenshot (121)

- Create a Group page :
Screenshot (120)

- Create Entity page :
Screenshot (122)

### Video:
https://www.loom.com/share/d9b68a3ddfec49aea3180ee341c34153

### Render Link :
https://budget-binder.onrender.com/

### CODE REVIEW

**Review by tresorsawasawa — COMMENTED** [review]
# STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @IsmaelMastronardi  ,:wave: :wave: 
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛑 🛑

You have submitted a project that doesn't correctly follow Gitflow. Kindly ensure that you have open your pull request from a `feature` branch to `dev` and not from `dev` to `main` branch.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

---
Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

---
_Invalid Code Review Request **Does not count** into the code reviews limit._

**Review by Gambit142 — COMMENTED** [review]
Hi @IsmaelMastronardi 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- You have submitted a project, that uses GitHub Flow instead of GitFlow. In a solo capstone project, you should use the GitFlow. This means that your pull request should come from a feature branch intending to merge into the dev branch. Kindly implement this change. 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by IsmaelMastronardi** [comment]
> Reference in new is
I am pretty sure this is wrong, as I cheked literally the projects from  all the people I know from Microverse, Everyone is merging from dev into main as this is a Capstone and it wouldn't make sense to have all the code in a single branch

**Review by Gambit142 — COMMENTED** [review]
Hi @IsmaelMastronardi 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- Kindly implement the first suggestion I made. If you feel I am wrong, you can ask for a second opinion from a senior code reviewer.  

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request closed without merging**
